### ISSUE TITLE
External provider integration

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/web#314]
Geek.Zone is expanding the range of member benefits that we are able to provide. These are provided by partner organisations to mutually promote
- Geek.Zone membership.
- the product or service of the partner organisation.

For example, Geek.Zone members might get 10% off all examples at [example.com](http://example.com). In order to tell example.com who to provide the discount to, we would need to provide personally identifiable information about every permitted member to example.com.

### Permission
As the partner is a third party, members must opt-in to allow their personally identifiable information to be shared with the partner. Members must be told
- the name of the organisation
- what benefit they provide to members
- what data needs to be provided to the partner in order for the member to receive that benefit.

NB
- The partner must be provided with the absolute minimum level of data required to function.
- The member must be able to revoke permission from the partner at any time.
- If the member revokes permission from the provider, the provider should regard this as a [GDPR 17](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-erasure/) instruction.

### Data Transfer
Most partners take our data via file transfer, usually XML or JSON via SFTP. They provide us with SFTP credentials and we send the file to them every *x* minutes. Most providers are not SSO enabled yet.

### Tasks
This is another one of my huge brain dumps. Do feel free to split into a project with smaller tickets.

- [ ] admin group UI for provider creation
- [ ] admin group UI to config data transfer - what fields are required? what format is required? etc
- [ ] member UI to opt into benefits
- [ ] member UI to advise member of their account credentials at each provider

admin group = accessible to those who are in the system administrators group #47 . Normal front end, not django admin.

**Comment by jamesgeddes** [comment]
Ideally this would be self serviced by the provider

**Comment by jamesgeddes** [comment]
I appreciate that I have been quite prescriptive here. Just to be clear, better solutions are very much welcome!
